# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Work',               url: 'work'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://www.instagram.com/_vasavinyoeri_/'}
- {icon: 'envelope', link:   'mailto:vasavin17m9@mail.ru'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'



related_posts: 'Other works...'

post_date_prefix: 'Written on'
